# Generated by Django 6.0.7 on 2026-07-24 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total_price',
        ),
        migrations.RemoveField(
            model_name='tableavai',
            name='table_number',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('D', 'Delivered')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableavai',
            name='number',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.menu'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.order'),
        ),
        migrations.AlterField(
            model_name='tableavai',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
