# Generated by Django 6.0.7 on 2026-07-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_cat_name_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableAvai',
            new_name='Table',
        ),
    ]
